// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokMultilink, StoryblokAsset } from "../storyblok.d.ts";
export interface ActionHeroSectionBlok {
  label?: string;
  href?: Exclude<
    StoryblokMultilink,
    { linktype?: "email" } | { linktype?: "asset" }
  >;
  component: "action_hero_section";
  _uid: string;
  [k: string]: unknown;
}

export interface DefaultPageBlok {
  body?: (
    | ActionHeroSectionBlok
    | DefaultPageBlok
    | HeaderSectionBlok
    | HeroSectionBlok
    | TextImageSectionBlok
  )[];
  title?: string;
  header?: (
    | ActionHeroSectionBlok
    | DefaultPageBlok
    | HeaderSectionBlok
    | HeroSectionBlok
    | TextImageSectionBlok
  )[];
  show_posts?: boolean;
  component: "default_page";
  _uid: string;
  [k: string]: unknown;
}

export interface HeaderSectionBlok {
  title?: string;
  svg?: string;
  component: "header_section";
  _uid: string;
  [k: string]: unknown;
}

export interface HeroSectionBlok {
  title?: string;
  from_color?: { color?: string };
  to_color?: { color?: string };
  action?: (
    | ActionHeroSectionBlok
    | DefaultPageBlok
    | HeaderSectionBlok
    | HeroSectionBlok
    | TextImageSectionBlok
  )[];
  component: "hero_section";
  _uid: string;
  [k: string]: unknown;
}

export interface TextImageSectionBlok {
  title?: string;
  description?: string;
  image?: StoryblokAsset;
  reverse?: boolean;
  component: "text_image_section";
  _uid: string;
  [k: string]: unknown;
}

export type ContentType = DefaultPageBlok;
